/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author PC BAO THONG
 */
import com.raven.service.ServiceMail;
import connectDB.ConnectDB;
import dao.NhanVien_DAO;
import entity.NhanVien;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Form_QuenMK extends javax.swing.JFrame {
    
    private NhanVien_DAO nvDAO;
    private ServiceMail sm;

    /**
     * Creates new form Form_QuenMK
     */
    public Form_QuenMK() {
        try {
            ConnectDB.getInstance().connect();
//            System.out.println("Ket noi Database thanh cong");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        nvDAO = new NhanVien_DAO();
        initComponents();
        setLocationRelativeTo(null);
        sm = new ServiceMail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNewPW = new textfield.PasswordField();
        txtXNNewPW = new textfield.PasswordField();
        txtMaNV = new textfield.TextField();
        btn_dangNhap = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel1.setBackground(new java.awt.Color(121, 188, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 40));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QUÊN MẬT KHẨU");
        jLabel7.setPreferredSize(new java.awt.Dimension(203, 40));
        jPanel1.add(jLabel7, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 465));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel2.setLayout(jPanel2Layout);

        txtNewPW.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtNewPW.setLabelText("Mật khẩu mới");
        txtNewPW.setPreferredSize(new java.awt.Dimension(400, 70));
        txtNewPW.setShowAndHide(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(txtNewPW, gridBagConstraints);

        txtXNNewPW.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtXNNewPW.setLabelText("Xác nhận mật khẩu");
        txtXNNewPW.setPreferredSize(new java.awt.Dimension(400, 70));
        txtXNNewPW.setShowAndHide(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(txtXNNewPW, gridBagConstraints);

        txtMaNV.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtMaNV.setLabelText("Mã nhân viên");
        txtMaNV.setPreferredSize(new java.awt.Dimension(400, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(txtMaNV, gridBagConstraints);

        btn_dangNhap.setBackground(new java.awt.Color(64, 71, 241));
        btn_dangNhap.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btn_dangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangNhap.setText("Đổi mật khẩu");
        btn_dangNhap.setBorder(null);
        btn_dangNhap.setPreferredSize(new java.awt.Dimension(200, 55));
        btn_dangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dangNhapMouseClicked(evt);
            }
        });
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(btn_dangNhap, gridBagConstraints);

        btn_out.setBackground(new java.awt.Color(255, 51, 51));
        btn_out.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btn_out.setForeground(new java.awt.Color(255, 255, 255));
        btn_out.setText("Trở về");
        btn_out.setBorder(null);
        btn_out.setPreferredSize(new java.awt.Dimension(150, 55));
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btn_out, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangNhapMouseClicked
        //new GiaoDienChinh().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangNhapMouseClicked

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        guiMail();
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_QuenMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_out;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private textfield.TextField txtMaNV;
    private textfield.PasswordField txtNewPW;
    private textfield.PasswordField txtXNNewPW;
    // End of variables declaration//GEN-END:variables

    private String taoCode() {
        int code = (int) (Math.random() * 100000);
        return code + "";
    }
    
    private void guiMail() {
        String maNV = txtMaNV.getText();
        String matKhauNew = new String(txtNewPW.getPassword());
        String matKhauXN = new String(txtXNNewPW.getPassword());
        if (matKhauNew.equals(matKhauXN) && !matKhauNew.isEmpty() && !matKhauXN.isEmpty()) {
            NhanVien nv = nvDAO.getNhanVienTheoMa(maNV);
            if (nv == null) {
                JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại trong hệ thống");
                return;
            }
            String code = taoCode();
            String email = nv.getEmailNV();
            sm.sendMain(email, code);
            new InputCode(code, maNV, matKhauNew).setVisible(true);
            hide();
        }else {
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận hoặc trống");
        }
        dispose();
    }  
}
