/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import connectDB.ConnectDB;
import dao.NhanVien_DAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author PC BAO THONG
 */
public class InputCode extends javax.swing.JFrame {

    private NhanVien_DAO nvDAO;
    private String maMail;
    private String maNhanVien;
    private String matKhau;

    /**
     * Creates new form InputCode
     */
    public InputCode(String code, String maNV, String mk) {
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        nvDAO = new NhanVien_DAO();
        maMail = code;
        maNhanVien = maNV;
        matKhau = mk;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnXN = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtXN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 188, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MÃ XÁC NHẬN");
        jPanel1.add(jLabel7, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 160));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0};
        jPanel2.setLayout(jPanel2Layout);

        btnXN.setBackground(new java.awt.Color(51, 153, 255));
        btnXN.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnXN.setForeground(new java.awt.Color(255, 255, 255));
        btnXN.setText("Xác nhận");
        btnXN.setPreferredSize(new java.awt.Dimension(150, 40));
        btnXN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(btnXN, gridBagConstraints);

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.setPreferredSize(new java.awt.Dimension(150, 40));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnThoat, gridBagConstraints);

        txtXN.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtXN.setPreferredSize(new java.awt.Dimension(350, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(txtXN, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNActionPerformed
        // TODO add your handling code here:
        String maNhap = txtXN.getText();
        if (maNhap.equalsIgnoreCase(maMail)) {
            if (update(maNhanVien, matKhau)) {
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
                dispose();
                new LoginForm().setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nhập sai mã, vui lòng nhập lại");
        }
    }//GEN-LAST:event_btnXNActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new Form_QuenMK().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXN;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtXN;
    // End of variables declaration//GEN-END:variables

    private boolean update(String maNV, String mk) {
        return nvDAO.updateMKNhanVien(maNV, mk);
    }
}
