/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.json.ParseException;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooserCellEditor;

import connectDB.ConnectDB;
import dao.KhachHang_DAO;
import entity.KhachHang;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;
import org.jdesktop.swingx.autocomplete.ComboBoxCellEditor;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_KH extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form GD_KH
     */
    private KhachHang_DAO kh_dao;
    private DefaultTableModel modelKH;

    public GD_KH() {
        try {
            ConnectDB.getInstance().connect();
            System.out.println("Ket noi Database thanh cong");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        kh_dao = new KhachHang_DAO();
        initComponents();
        tableKhachHang();
    }

    private void tableKhachHang() {
        PromptSupport.setPrompt("Nhập số điện thoại", txtTimKH);
        tableKH.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableKH.getTableHeader().setOpaque(false);
        tableKH.getTableHeader().setBackground(new Color(32, 136, 203));
        tableKH.getTableHeader().setForeground(new Color(255, 255, 255));
        modelKH = (DefaultTableModel) tableKH.getModel();
        napDuLieuKH();
    }

    private void napDuLieuKH() {
        ArrayList<KhachHang> dsKH;
        dsKH = kh_dao.getAllKhachHang();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        for (KhachHang kh : dsKH) {

            modelKH.addRow(new Object[]{kh.getMaKH(), kh.getSoCCCD(), kh.getHoKH(), kh.getTenKH(), formatter.format(kh.getNamSinhKH()), chuyenGTSangString(kh), kh.getSdtKH(), kh.getEmailKH()});
        }
    }

    public String chuyenGTSangString(KhachHang kh) {
        if (kh.isGioiTinhKH() == true) {
            return "Nam";
        }
        return "Nữ";
    }

    public void xoaTrang() {
        txtMaKH.setText("");
        txtCCCD.setText("");
        txtHoKH.setText("");
        txtTenKH.setText("");
        txtSDT.setText("");
        radioNam1.setSelected(false);
        radioNu1.setSelected(false);
        dateNgaySinh.setDate(null);
        txtMaKH.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngGioiTinh = new javax.swing.ButtonGroup();
        GD_KhachHang = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHoKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTimKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        radioNu1 = new javax.swing.JRadioButton();
        radioNam1 = new javax.swing.JRadioButton();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKH = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        GD_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        GD_KhachHang.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        GD_KhachHang.setMaximumSize(new java.awt.Dimension(1200, 520));
        GD_KhachHang.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(1200, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 300));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel4.setText("Mã khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel4, gridBagConstraints);

        txtMaKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtMaKH.setEnabled(false);
        txtMaKH.setMinimumSize(new java.awt.Dimension(200, 30));
        txtMaKH.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(txtMaKH, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setText("Họ khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jLabel5, gridBagConstraints);

        txtHoKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtHoKH.setMinimumSize(new java.awt.Dimension(200, 30));
        txtHoKH.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel3.add(txtHoKH, gridBagConstraints);

        txtTenKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTenKH.setMinimumSize(new java.awt.Dimension(200, 30));
        txtTenKH.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel3.add(txtTenKH, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel7, gridBagConstraints);

        txtSDT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtSDT.setMinimumSize(new java.awt.Dimension(200, 30));
        txtSDT.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel3.add(txtSDT, gridBagConstraints);

        btnTim.setBackground(new java.awt.Color(121, 188, 215));
        btnTim.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(btnTim, gridBagConstraints);

        btnCapNhat.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhat.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật thông tin");
        btnCapNhat.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        jPanel3.add(btnCapNhat, gridBagConstraints);

        btnThem.setBackground(new java.awt.Color(61, 102, 255));
        btnThem.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        btnThem.setText("Thêm khách hàng");
        btnThem.setPreferredSize(new java.awt.Dimension(200, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        jPanel3.add(btnThem, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("Tên khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel9.setText("CCCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel9, gridBagConstraints);

        txtTimKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTimKH.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        jPanel3.add(txtTimKH, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel10.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel10, gridBagConstraints);

        txtCCCD.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtCCCD.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel3.add(txtCCCD, gridBagConstraints);

        radioNu1.setBackground(new java.awt.Color(255, 255, 255));
        btngGioiTinh.add(radioNu1);
        radioNu1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNu1.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel3.add(radioNu1, gridBagConstraints);

        radioNam1.setBackground(new java.awt.Color(255, 255, 255));
        btngGioiTinh.add(radioNam1);
        radioNam1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNam1.setText("Nam");
        radioNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNam1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(radioNam1, gridBagConstraints);

        dateNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        dateNgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateNgaySinh.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        dateNgaySinh.setMaximumSize(new java.awt.Dimension(250, 30));
        dateNgaySinh.setMinimumSize(new java.awt.Dimension(250, 30));
        dateNgaySinh.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel3.add(dateNgaySinh, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel11.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel11, gridBagConstraints);

        btnLamMoi.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setMaximumSize(new java.awt.Dimension(70, 40));
        btnLamMoi.setMinimumSize(new java.awt.Dimension(70, 30));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(130, 30));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(btnLamMoi, gridBagConstraints);

        btnXoa.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa.setText("Xóa trắng");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa.setMaximumSize(new java.awt.Dimension(120, 40));
        btnXoa.setMinimumSize(new java.awt.Dimension(70, 30));
        btnXoa.setPreferredSize(new java.awt.Dimension(130, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(btnXoa, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel12.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel12, gridBagConstraints);

        txtEmail.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        jPanel3.add(txtEmail, gridBagConstraints);

        GD_KhachHang.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel7.setMinimumSize(new java.awt.Dimension(1200, 220));
        jPanel7.setPreferredSize(new java.awt.Dimension(1200, 220));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jScrollPane1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 600));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "CCCD", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại"
            }
        ));
        tableKH.setRowHeight(25);
        tableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKH);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        GD_KhachHang.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(GD_KhachHang, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (valid()) {
            them();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void radioNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNam1ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoaTrang();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKHMouseClicked
        // TODO add your handling code here:
        int r = tableKH.getSelectedRow();
        txtMaKH.setText(modelKH.getValueAt(r, 0).toString());
        txtHoKH.setText(modelKH.getValueAt(r, 2).toString());//ho
        txtTenKH.setText(modelKH.getValueAt(r, 3).toString());//ten	
        txtSDT.setText(modelKH.getValueAt(r, 6).toString());//sdt
        txtCCCD.setText(modelKH.getValueAt(r, 1).toString());//cccd
        KhachHang kh = kh_dao.getKhachHangTheoMa(txtMaKH.getText());
        txtEmail.setText(kh.getEmailKH());//email
        String gt = modelKH.getValueAt(r, 5).toString();
        if ("Nam".equalsIgnoreCase(gt)) {
            radioNam1.setSelected(true);
            radioNu1.setSelected(false);
        } else {
            radioNu1.setSelected(true);
            radioNam1.setSelected(false);
        }
        try {
            Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String) modelKH.getValueAt(r, 4));
            dateNgaySinh.setDate(date);
        } catch (java.text.ParseException ex) {
            Logger.getLogger(GD_KH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableKHMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (valid()) {
            update();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        Object o = evt.getSource();
        if (o.equals(btnTim)) {
            String sdt = txtTimKH.getText().trim();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            KhachHang kh = kh_dao.layKhachHangTheoSDT(sdt);
            xoaTrang();
            modelKH.getDataVector().removeAllElements();
            String[] data = {kh.getMaKH(), kh.getSoCCCD(), kh.getHoKH(), kh.getTenKH(), formatter.format(kh.getNamSinhKH()), chuyenGTSangString(kh), kh.getSdtKH(), kh.getEmailKH()};
            modelKH.addRow(data);
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_KhachHang;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup btngGioiTinh;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam1;
    private javax.swing.JRadioButton radioNu1;
    private javax.swing.JTable tableKH;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKH;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        // TODO Auto-generated method stub
    }

    private void lamMoi() {
        xoaTrang();
        modelKH.setRowCount(0);
        napDuLieuKH();
    }

    private void update() {
        // TODO Auto-generated method stub

        int row = tableKH.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!!");
        }
        if (row >= 0) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String gt = "Nữ";
            if (radioNam1.isSelected() && !radioNu1.isSelected()) {

                gt = "Nam";
            }

            String ngaySinh = dateFormat.format(dateNgaySinh.getDate());
            KhachHang kh = reverSPFromTextField();

            if (kh_dao.updateKhachHang(kh)) {

                tableKH.setValueAt(txtCCCD.getText(), row, 1);
                tableKH.setValueAt(txtHoKH.getText(), row, 2);
                tableKH.setValueAt(txtTenKH.getText(), row, 3);
                tableKH.setValueAt(txtSDT.getText(), row, 6);
                tableKH.setValueAt(gt, row, 5);
                tableKH.setValueAt(ngaySinh, row, 4);
                lamMoi();
                JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Sửa không thành công!!");
            }

        }

    }

    private boolean valid() {
        String ho, ten, cccd, sdt;
        ho = txtHoKH.getText().trim();
        ten = txtTenKH.getText().trim();
        cccd = txtCCCD.getText().trim();
        sdt = txtSDT.getText().trim();
        if (!(ho.length() > 0 && ho.matches("^[\\p{L}]*(?:\\h+[\\p{L}]*)*$"))) {
            JOptionPane.showMessageDialog(null, "Error: Họ khách hàng không có số hay kí tự đặc biệt");
            txtHoKH.requestFocus();
            return false;
        } else if (!(ten.length() > 0 && ten.matches("^[\\p{L}]*$"))) {
            JOptionPane.showMessageDialog(null, "Error: Tên khách hàng là 1 từ, không có số, hay kí tự đặc biệt");
            txtTenKH.requestFocus();
            return false;
        } else if (!(sdt.length() > 0 && sdt.matches("^\\d{10}$"))) {
            JOptionPane.showMessageDialog(null, "Error: Số điện thoại là 1 dãy số nguyên có 10 số");
            txtSDT.requestFocus();
            return false;
        } else if (!(cccd.length() >= 0 && cccd.matches("^\\d{12}$"))) {
            JOptionPane.showMessageDialog(null, "CCCD phải 12 số");
            txtCCCD.requestFocus();
            return false;
        }
        return true;
    }

    public KhachHang reverSPFromTextField() {
        radioNu1.setSelected(false);
        radioNam1.setSelected(false);
        String ma = txtMaKH.getText();
        String ho = txtHoKH.getText();
        String ten = txtTenKH.getText();
        String sdt = txtSDT.getText();
        String cccd = txtCCCD.getText();
        String email = txtEmail.getText();
        Date ngaySinh = dateNgaySinh.getDate();
        boolean gt = true;
        if (radioNu1.isSelected()) {
            gt = false;
        }

        return new KhachHang(ma, cccd, ho, ten, ngaySinh, gt, sdt, email);
    }

    public void them() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ma = kh_dao.maKH_Auto();
        String ho = txtHoKH.getText();
        String ten = txtTenKH.getText();
        String sdt = txtSDT.getText();
        String cccd = txtCCCD.getText();
        String email = txtEmail.getText();
        String ngaySinh = dateFormat.format(dateNgaySinh.getDate());
        Date dNgaySinh = dateNgaySinh.getDate();
        String gt = "Nam";
        boolean bgt = true;
        if (radioNu1.isSelected()) {
            gt = "Nữ";
            bgt = false;
        }

        KhachHang kh = new KhachHang(ma, cccd, ho, ten, dNgaySinh, bgt, sdt, email);
        if (kh_dao.insertKhachHang(kh)) {
            String[] data = {ma, cccd, ho,
                ten, ngaySinh, gt, sdt};
            modelKH.addRow(data);
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành Công !");
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        // TODO Auto-generated method stub

    }

    @Override
    public void mouseReleased(MouseEvent e) {
        // TODO Auto-generated method stub

    }

    @Override
    public void mouseEntered(MouseEvent e) {
        // TODO Auto-generated method stub

    }

    @Override
    public void mouseExited(MouseEvent e) {
        // TODO Auto-generated method stub

    }
}
