/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import slide.Slide1;
import slide.Slide2;
import slide.Slide3;

/**
 *
 * @author PC BAO THONG
 */
public class GD_TrangChu extends javax.swing.JPanel {

    /**
     * Creates new form GD_DV
     */
    public GD_TrangChu() {
        initComponents();
        slideshow1.initSlideshow(new Slide1(), new Slide2(), new Slide3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slideshow1 = new slideshow.Slideshow();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 520));
        setLayout(new java.awt.BorderLayout());

        slideshow1.setPreferredSize(new java.awt.Dimension(1200, 520));
        add(slideshow1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private slideshow.Slideshow slideshow1;
    // End of variables declaration//GEN-END:variables
    
}
