/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import chart.ModelPolarAreaChart;
import connectDB.ConnectDB;
import dao.HoaDon_DAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC BAO THONG
 */
public class ThongKeDoanhThuNgay extends javax.swing.JPanel {

    private HoaDon_DAO hoadonDAO;

    /**
     * Creates new form ThongKeDoanhThuNgay
     */
    public ThongKeDoanhThuNgay() {
        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        hoadonDAO = new HoaDon_DAO();
        date.setDate(new Date());
        Date ngay = date.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(ngay);
        System.out.println("Ngày tháng năm được chọn: " + dateString);
        themVaoChar(dateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        polarAreaChart = new chart.PolarAreaChart();
        jPanel1 = new javax.swing.JPanel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtTongDT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDoanhThuPT = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTongDTP = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTongDTDV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDoanhThuPV = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 520));

        polarAreaChart.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        polarAreaChart.setMaximumSize(new java.awt.Dimension(800, 32803));
        polarAreaChart.setMinimumSize(new java.awt.Dimension(800, 42));
        polarAreaChart.setPreferredSize(new java.awt.Dimension(700, 520));
        add(polarAreaChart);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 520));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel1.setLayout(jPanel1Layout);

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        date.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(date, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel3.setText("Tổng doanh thu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtTongDT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTongDT.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtTongDT, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setText("Doanh thu phòng thường");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        txtDoanhThuPT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDoanhThuPT.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDoanhThuPT, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Doanh thu phòng VIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        txtTongDTP.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTongDTP.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtTongDTP, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel9.setText("Tổng doanh thu phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel9, gridBagConstraints);

        txtTongDTDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTongDTDV.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtTongDTDV, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel11.setText("Tổng doanh thu dịch vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel11, gridBagConstraints);

        txtDoanhThuPV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDoanhThuPV.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDoanhThuPV, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton1.setText("Xem");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jButton1, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date ngay = date.getDate();
        if(ngay.after(new Date())){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày trước ngày hiện tại");
            date.setDate(new Date());
            return;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(ngay);
        System.out.println("Ngày tháng năm được chọn: " + dateString);
        themVaoChar(dateString);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void themVaoChar(String ngay) {
        polarAreaChart.clear();
        Double tongDT = hoadonDAO.layTongDoanhThuTheoNgay(ngay);
        Double tongDTDV = hoadonDAO.layTongDoanhThuDVTheoNgay(ngay);
        Double tongDTP = tongDT - tongDTDV;
        Double tongDTPV = hoadonDAO.layTongDoanhThuTheoPVTheoNgay(ngay);
        Double tongDTPT = tongDTP - tongDTPV;
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,##0.##", symbols);
        txtTongDT.setText(df.format(tongDT) + " VND");
        txtTongDTDV.setText(df.format(tongDTDV) + " VND");
        txtTongDTP.setText(df.format(tongDTP) + " VND");
        txtDoanhThuPT.setText(df.format(tongDTPT) + " VND");
        txtDoanhThuPV.setText(df.format(tongDTPV) + " VND");
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(52, 148, 203), "Doanh thu phòng", tongDTP));
        polarAreaChart.addItem(new ModelPolarAreaChart(new Color(175, 67, 237), "Doanh thu dịch vụ", tongDTDV));
        polarAreaChart.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private chart.PolarAreaChart polarAreaChart;
    private javax.swing.JLabel txtDoanhThuPT;
    private javax.swing.JLabel txtDoanhThuPV;
    private javax.swing.JLabel txtTongDT;
    private javax.swing.JLabel txtTongDTDV;
    private javax.swing.JLabel txtTongDTP;
    // End of variables declaration//GEN-END:variables
}
