/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.raven.chart.ModelChart;
import connectDB.ConnectDB;
import dao.HoaDon_DAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;

/**
 *
 * @author PC BAO THONG
 */
public class ThongKeDoanhThuThang extends javax.swing.JPanel {

    private HoaDon_DAO hoadonDAO;

    /**
     * Creates new form ThongKeDoanhThuThang
     */
    public ThongKeDoanhThuThang() {
        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        hoadonDAO = new HoaDon_DAO();
        addItemCombobox();
        initComponents();
        String nam = comboNam.getSelectedItem().toString();
        String thang = comboThang.getSelectedItem().toString();
        chart.addLegend("Tổng doanh thu", new Color(245, 189, 135));
        chart.clear();
        themVaoChart(nam, thang);
        chart.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chart = new com.raven.chart.Chart();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTongDoanhThu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDoanhThuPT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDoanhThuPV = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDoanhThuDV = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTongDTPhong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 520));
        setLayout(new java.awt.GridBagLayout());

        chart.setPreferredSize(new java.awt.Dimension(800, 520));
        add(chart, new java.awt.GridBagConstraints());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 520));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel1.setText("Năm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel2.setText("Tổng doanh thu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtTongDoanhThu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTongDoanhThu.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtTongDoanhThu, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel4.setText("Doanh thu phòng thường");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        txtDoanhThuPT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDoanhThuPT.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDoanhThuPT, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel6.setText("Doanh thu phòng VIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        txtDoanhThuPV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDoanhThuPV.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDoanhThuPV, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("Doanh thu dịch vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel8, gridBagConstraints);

        txtDoanhThuDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDoanhThuDV.setText("jLabel9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDoanhThuDV, gridBagConstraints);

        comboNam.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboNam.setFocusable(false);
        comboNam.setPreferredSize(new java.awt.Dimension(150, 30));
        comboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(comboNam, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel3.setText("Tổng doanh thu phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtTongDTPhong.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTongDTPhong.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtTongDTPhong, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setText("Tháng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        comboThang.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboThang.setPreferredSize(new java.awt.Dimension(150, 30));
        comboThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboThangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(comboThang, gridBagConstraints);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void comboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNamActionPerformed
        // TODO add your handling code here:
        chart.clear();
        String nam = comboNam.getSelectedItem().toString();
        String thang = comboThang.getSelectedItem().toString();
        themVaoChart(nam, thang);
        chart.start();
    }//GEN-LAST:event_comboNamActionPerformed

    private void comboThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboThangActionPerformed
        // TODO add your handling code here:
        chart.clear();
        String nam = comboNam.getSelectedItem().toString();
        String thang = comboThang.getSelectedItem().toString();
        themVaoChart(nam, thang);
        chart.start();
    }//GEN-LAST:event_comboThangActionPerformed
    private void addItemCombobox() {
        ArrayList<Integer> i = hoadonDAO.layNamTuHoaDon();
        if (comboNam.getSelectedItem() == null) {
            for (Integer integer : i) {
                comboNam.addItem(integer + "");
            }
        }
    }

    private void themVaoChart(String nam, String thang) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,##0.##", symbols);
        Double tongDT = hoadonDAO.layTongDoanhThuTheoThang(nam, thang);
        Double giaDV = hoadonDAO.layTongDoanhThuDVTheoThang(nam, thang);
        Double tongDTP = tongDT - giaDV;
        Double tongDTPV = hoadonDAO.layTongDoanhThuTheoPVTheoThang(nam, thang);
        Double tongDTPT = tongDTP - tongDTPV;
        txtTongDoanhThu.setText(df.format(tongDT) + " VND");
        txtDoanhThuDV.setText(df.format(giaDV) + " VND");
        txtTongDTPhong.setText(df.format(tongDTP) + " VND");
        txtDoanhThuPV.setText(df.format(tongDTPV) + " VND");
        txtDoanhThuPT.setText(df.format(tongDTPT) + " VND");
        int month = Integer.parseInt(thang);
        System.out.println(month);
        int year = Integer.parseInt(nam);

// Tạo đối tượng Calendar
        Calendar calendar = Calendar.getInstance();

// Đặt tháng và năm
        calendar.set(year, month - 1, 1);

// Lấy số ngày cuối cùng của tháng
        int lastDay = calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
// Xuất tất cả trong tháng
        Double[] a = hoadonDAO.layDoanhThuTheoThang(nam, thang, lastDay);
        ArrayList<Integer> i = new ArrayList<>();
        for (int day = 1; day <= lastDay; day++) {
            i.add(day);
        }
        chart.clear();
        int j = 0;
        for (Integer integer : i) {
            chart.addData(new ModelChart(integer + "", new double[]{a[j]}));
            j++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    private static final javax.swing.JComboBox<String> comboNam = new javax.swing.JComboBox<>();
    private static final javax.swing.JComboBox<String> comboThang = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDoanhThuDV;
    private javax.swing.JLabel txtDoanhThuPT;
    private javax.swing.JLabel txtDoanhThuPV;
    private javax.swing.JLabel txtTongDTPhong;
    private javax.swing.JLabel txtTongDoanhThu;
    // End of variables declaration//GEN-END:variables
}
